server:
  port: 8180

domain:
  account:
    name: account
  accountBank:
    name: accountBank

spring:
  application:
    name: awesome-account-service
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;
    username: sa
    password: null
    driver-class-name: org.h2.Driver
    initialization-mode: always
  h2:
    console:
      enabled: true
  cloud:
    stream:
      binders:
        rabbitmq:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.99.100
                port: 5672
                username: labs
                password: awesome-rabbitmq
      bindings:
        accountCreated:
          destination: accountExchange
          group: account.accountCreated
          content-type: application/json
        AccountBankOutput:
          destination: accountBankExchange
          content-type: application/json
        AccountOutput:
          destination: accountExchange
          content-type: application/json
      rabbit:
        bindings:
          accountCreated:
            consumer:
              autoBindDlq: true
              bindingRoutingKey: account.AccountCreated.#
          AccountBankOutput:
            producer:
              routing-key-expression: headers['routeTo']
          AccountOutput:
            producer:
              routing-key-expression: headers['routeTo']

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"