server:
  port: 8181

domain:
  name: cart

spring:
  application:
    name: awesome-cart-service
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;
    username: sa
    password: null
    driver-class-name: org.h2.Driver
    initialization-mode: always
  h2:
    console:
      enabled: true
  cloud:
    stream:
      binders:
        rabbitmq:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 52.79.63.17
                port: 5672
                username: labs
                password: awesome-rabbitmq
      bindings:
        productAmountAdded:
          destination: productExchange
          group: cart.productAmountAdded
          content-type: application/json
        productSoldOut:
          destination: productExchange
          group: cart.productSoldOut
          content-type: application/json
        CartOutput:
          destination: cartExchange
          content-type: application/json
      rabbit:
        bindings:
          productAmountAdded:
            consumer:
              autoBindDlq: true
              bindingRoutingKey: product.ProductAmountAdded.#
          productSoldOut:
            consumer:
              autoBindDlq: true
              bindingRoutingKey: product.ProductSoldOut.#
          CartOutput:
            producer:
              routing-key-expression: headers['routeTo']
              
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"