server:
  port: 8182

domain:
  name: order
  
spring:
  application:
    name: awesome-order-service
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;
    username: sa
    password: null
    driver-class-name: org.h2.Driver
    initialization-mode: always
  h2:
    console:
      enabled: true
  cloud:
    stream:
      binders:
        rabbitmq:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 34.211.184.139
                port: 5672
                username: labs
                password: awesome-rabbitmq
      bindings:
        productAmountSubtractFailed:
          destination: productExchange
          group: order.productAmountSubtractFailed
          content-type: application/json
        OrderOutput:
          destination: orderExchange
          content-type: application/json
      rabbit:
        bindings:
          productAmountSubtractFailed:
            consumer:
              autoBindDlq: true
              bindingRoutingKey: product.ProductAmountSubtractFailed.#
          OrderOutput:
            producer:
              autoBindDlq: true
              routing-key-expression: headers['routeTo']
              

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"